### ISSUE TITLE
Can't send tokens

### ISSUE THREAD

**Issue by scuba323** [ahmetozlu/defi_yield_farming#6]
````
truffle exec scripts/issue-tokens.js

Using network 'development'.

Error: ENOENT: no such file or directory, open '/home/eth/DAPPS/defi_yield_farming/scripts/issue-tokens.js'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at Object.file (/usr/local/lib/node_modules/truffle/build/webpack:/packages/require/require.js:28:1)
    at Object.exec (/usr/local/lib/node_modules/truffle/build/webpack:/packages/require/require.js:121:1)
    at internal/util.js:308:30
    at new Promise (<anonymous>)
    at bound exec (internal/util.js:307:12)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/exec.js:75:1)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:172:1)
Truffle v5.4.3 (core: 5.4.3)
Node v14.17.0
````

**Comment by ahmetozlu** [comment]
Fixed, please try again.
